version: '3.7'
services:
   
  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: webapp
      MYSQL_USER: cto
      MYSQL_PASSWORD: qwerty

  webapp:
    image: nginx:1.17.3-alpine
    volumes:
      - ./webapp/:/app/
      - ./vhosts/:/etc/nginx/conf.d/
    working_dir: /app/
    ports:
      - 80:80
    environment:
      APP_ENV: development
    depends_on:
      - webapp-php
    restart: 'no' 

  webapp-php:
    build: ./php
    working_dir: /app/
    volumes:
      - ./webapp/:/app/
    environment:
      APP_ENV: development
    depends_on:
      - db
    restart: 'no'