version: '3.7'
services:
   
  db-master:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password # plugin autentykacyjny wstecznie kompatybilny ze starszymi klientami
    volumes:
      - ./db-config/master.cnf:/etc//mysql/conf.d/master.cnf
      - ./db-dump:/db-dump
    ports:
      - 3306:3306
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: webapp
      MYSQL_USER: cto
      MYSQL_PASSWORD: qwerty

  db-slave:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password # plugin autentykacyjny wstecznie kompatybilny ze starszymi klientami
    volumes:
      - ./db-config/slave.cnf:/etc//mysql/conf.d/slave.cnf
      - ./db-dump:/db-dump
    ports:
      - 3307:3306
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: webapp
      MYSQL_USER: cto
      MYSQL_PASSWORD: qwerty

  webapp:
    image: nginx:1.17.3-alpine
    volumes:
      - ./webapp/:/app/
      - ./vhosts/:/etc/nginx/conf.d/
    working_dir: /app/
    ports:
      - 80:80
    depends_on:
      - webapp-php
    restart: 'no' 

  webapp-php:
    image: php:7.2-fpm-alpine
    working_dir: /app/
    volumes:
      - ./webapp/:/app/
    environment:
      APP_ENV: development
    depends_on:
      - db-master
    restart: 'no'